-- MySQL Script generated by MySQL Workbench
-- 08/29/16 14:05:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testteam8db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testteam8db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testteam8db` DEFAULT CHARACTER SET utf8 ;
USE `testteam8db` ;

-- -----------------------------------------------------
-- Table `testteam8db`.`Portfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testteam8db`.`Portfolios` (
  `PortfolioID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `PortfolioName` VARCHAR(45) NULL DEFAULT 'New Portfolio' COMMENT '',
  `PortfolioType` VARCHAR(45) NULL DEFAULT 'My new portfolio' COMMENT '',
  PRIMARY KEY (`PortfolioID`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testteam8db`.`CompaniesHeldinPortfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testteam8db`.`CompaniesHeldinPortfolios` (
  `CompanyID` INT(11) NOT NULL COMMENT '',
  `Portfolio_PortfolioID` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`CompanyID`)  COMMENT '',
  INDEX `fk_portfoliodetails_Portfolio1_idx` (`Portfolio_PortfolioID` ASC)  COMMENT '',
  CONSTRAINT `fk_portfoliodetails_Portfolio1`
    FOREIGN KEY (`Portfolio_PortfolioID`)
    REFERENCES `testteam8db`.`Portfolios` (`PortfolioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testteam8db`.`CompanyStockInfoByDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testteam8db`.`CompanyStockInfoByDate` (
  `CompanyID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `InfoDate` DATE NULL DEFAULT NULL COMMENT '',
  `open` DOUBLE NULL COMMENT '',
  `high` DOUBLE NULL DEFAULT NULL COMMENT '',
  `low` DOUBLE NULL DEFAULT NULL COMMENT '',
  `close` DOUBLE NULL DEFAULT NULL COMMENT '',
  `Volume` INT(11) NULL DEFAULT NULL COMMENT '',
  `portfoliodetails_CompanyID` INT(11) NOT NULL COMMENT '',
  `ticker` VARCHAR(45) NULL COMMENT '',
  INDEX `fk_stocks_portfoliodetails1_idx` (`portfoliodetails_CompanyID` ASC)  COMMENT '',
  PRIMARY KEY (`CompanyID`)  COMMENT '',
  CONSTRAINT `fk_stocks_portfoliodetails1`
    FOREIGN KEY (`portfoliodetails_CompanyID`)
    REFERENCES `testteam8db`.`CompaniesHeldinPortfolios` (`CompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `testteam8db`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testteam8db`.`Transactions` (
  `TransactionID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TransactionDate` DATE NULL DEFAULT NULL COMMENT '',
  `NumberOfUnits` INT(11) NULL DEFAULT NULL COMMENT '',
  `UnitPrice` DOUBLE NULL COMMENT '',
  `CompaniesHeldinPortfolios_CompanyID` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`TransactionID`)  COMMENT '',
  INDEX `fk_transactions_CompaniesHeldinPortfolios1_idx` (`CompaniesHeldinPortfolios_CompanyID` ASC)  COMMENT '',
  CONSTRAINT `fk_transactions_CompaniesHeldinPortfolios1`
    FOREIGN KEY (`CompaniesHeldinPortfolios_CompanyID`)
    REFERENCES `testteam8db`.`CompaniesHeldinPortfolios` (`CompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
